#!/bin/sh

# ----------REMARQUE IMPORTANTE-------------------------
#ilfichier hedha fih les opérateurs li mtaa sh , weli normalement yemshiw aala ay shell 

a=10
b=20

#addition
val=`expr $a + $b`
echo "a + b : $val"

#substraction
val=`expr $a - $b`
echo "a - b : $val"

#multiplication
val=`expr $a \* $b`
echo "a * b : $val"

#division euclidienne
val=`expr $b / $a`
echo "b / a : $val"

#modulo
val=`expr $b % $a`
echo "b % a : $val"

#equality
if [ $a -eq $b ]
then
   echo "a is equal to b"
fi

#inequality
if [ $a != $b ]
then
   echo "a is not equal to b"
fi

#--------------------------------Relational operators---------------------------------------------

a=10
b=20

if [ $a -eq $b ]
then
   echo "$a -eq $b : a is equal to b"
else
   echo "$a -eq $b: a is not equal to b"
fi

if [ $a -ne $b ]
then
   echo "$a -ne $b: a is not equal to b"
else
   echo "$a -ne $b : a is equal to b"
fi

if [ $a -gt $b ]
then
   echo "$a -gt $b: a is greater than b"
else
   echo "$a -gt $b: a is not greater than b"
fi

if [ $a -lt $b ]
then
   echo "$a -lt $b: a is less than b"
else
   echo "$a -lt $b: a is not less than b"
fi

if [ $a -ge $b ]
then
   echo "$a -ge $b: a is greater or  equal to b"
else
   echo "$a -ge $b: a is not greater or equal to b"
fi

if [ $a -le $b ]
then
   echo "$a -le $b: a is less or  equal to b"
else
   echo "$a -le $b: a is not less or equal to b"
fi

#-------------------------------------logical operators----------------------------
a=10
b=20

# ! operator 
if [ $a != $b ]
then
   echo "$a != $b : a is not equal to b"
else
   echo "$a != $b: a is equal to b"
fi

# and operator 
if [ $a -lt 100 -a $b -gt 15 ]
then
   echo "$a -lt 100 -a $b -gt 15 : returns true"
else
   echo "$a -lt 100 -a $b -gt 15 : returns false"
fi

# or operator 
if [ $a -lt 100 -o $b -gt 100 ]
then
   echo "$a -lt 100 -o $b -gt 100 : returns true"
else
   echo "$a -lt 100 -o $b -gt 100 : returns false"
fi


#-----------------------mixed examples--------------------------
a=10

# test si un nombre est divisible par 2
if [ `expr $a % 2` -eq 0 ]
then 
   echo "$a is divisible by 2 "
else 
  echo "$a is not divisible by 2 "
fi


#------------------------------String operators-------------------------------

echo "-------------------------String operators------------------------"
a="abc"
b="efg"

if [ $a = $b ]
then
   echo "$a = $b : a is equal to b"
else
   echo "$a = $b: a is not equal to b"
fi

if [ $a != $b ]
then
   echo "$a != $b : a is not equal to b"
else
   echo "$a != $b: a is equal to b"
fi

if [ -z $a ]
then
   echo "-z $a : string length is zero"
else
   echo "-z $a : string length is not zero"
fi

if [ -n $a ]
then
   echo "-n $a : string length is not zero"
else
   echo "-n $a : string length is zero"
fi

if [ $a ]
then
   echo "$a : string is not empty"
else
   echo "$a : string is empty"
fi


#--------------------------------file operators-----------------------------
#!/bin/sh

#creation d'un fichier dans le Desktop
touch /home/`whoami`/Desktop/FichierDeTest
file="/home/`whoami`/Desktop/FichierDeTest"
if [ -r $file ]
then
   echo "File has read access"
else
   echo "File does not have read access"
fi

if [ -w $file ]
then
   echo "File has write permission"
else
   echo "File does not have write permission"
fi

if [ -x $file ]
then
   echo "File has execute permission"
else
   echo "File does not have execute permission"
fi

if [ -f $file ]
then
   echo "File is an ordinary file"
else
   echo "This is sepcial file"
fi

if [ -d $file ]
then
   echo "File is a directory"
else
   echo "This is not a directory"
fi

if [ -s $file ]
then
   echo "File size is not zero"
else
   echo "File size is zero"
fi

if [ -e $file ]
then
   echo "File exists"
else
   echo "File does not exist"
fi























